### ISSUE TITLE
Loading cashew plantation dataset

### ISSUE THREAD

**Issue by tomsynativ** [vishalned/MMEarth-train#4]
I have installed GEO-Bench via pip (and ran `geobench-test` which passed). It downloads benchmark `segmentation_v1.0` as default, so I changed:

- `segmentation_v0.9.1` to `segmentation_v1.0` everywhere it was hardcoded.
- `m-cashew-plantation` to `m-cashew-plant` as it seems like they changed the key.

However, my folder `../dataset/segmentation_v1.0/m-cashew-plant` does not contain `label_map.json` nor `label_stats.json` which `class geobench_dataset(Dataset)` in `custom_dataset.py` tries to retrieve.

Can you confirm whether this is an issue that has arisen due to the update of the segmentation benchmark or if there might be something else going wrong on my side? Thanks!

**Comment by vishalned** [comment]
should be fixed now
