### ISSUE TITLE
Possible Typo

### ISSUE THREAD

**Issue by nilsleh** [vishalned/MMEarth-train#5]
Hi, is [this](https://github.com/vishalned/MMEarth-train/blob/8d6114e8e3ccb5ca5d98858e742dac24350b64fd/MODALITIES.py#L39) a possible typo and should be "sentinel2_cloudprob" instead of "sentinel2_cloudprod"? 

Edit:
- in the dataset .h5 file (atleast in the 100k) version, the key name is "sentinel2_cloudproD"
- in the no data values it is "sentinel2_cloudproD"
- in the full modalities names it is "sentinel2_cloudproB"

**Comment by vishalned** [comment]
hey, thanks for letting me know. this is a typo. A small note: the repo is being fixed at the moment, and have quite some changes being pushed. There is an "update" at the beginning of the repo, and the expected time it will be ready is the first week of august.
